### PR TITLE
Lowercase order id when searching

### LINKED ISSUE #309: Entering Order ID with uppercase letters
# Description
Order is not found if the x in 0x is in upper cases

# To Reproduce:
Steps to reproduce the behaviour:
- If my recent activitiy is cleared in GP swap and want to trace a trade I will have to look for the order ID in Etherscan. 
-  Here the Order ID is in uppercase letters
1. Approach: Insert copied order ID and paste into explorer searchbar and add "0x"
a.) 0**x**804B97B985.... 
b.) 0**X**804B97B985....
2. Approach add it to the url: 
a) https://pr307--gpui.review.gnosisdev.com/rinkeby/orders/0**x**804B97B985....
b) https://pr307--gpui.review.gnosisdev.com/rinkeby/orders/0**X**804B97B985....

# Expected Behaviour
User gets directed to Order Details page

# Actual Behaviour
If the x is in lowercase the user gets directed to the order details page. 
If the user inserted an uppercase X the order is not found

# Screenshots/Videos
Bildschirmfoto 2021-03-16 um 11 41 04
Bildschirmfoto 2021-03-16 um 11 41 18

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #309 

Order id search is now case insensitive

## Update 2021/03/24

`orderid` is extracted from URL via regex. As long as the orderId is in there continuously, everything around it is ignored.
Example:
- https://pr323--gpui.review.gnosisdev.com/orders/%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%800XC31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80/
- https://pr323--gpui.review.gnosisdev.com/rinkeby/orders/kjldfasldhflasdhfa0xc31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb0589273n4c12b3b1f19234/
- https://pr323--gpui.review.gnosisdev.com/rinkeby/orders/"0xc31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05"/

Same applies to search input. Anything in there will be added to the URL, which in turn will be "cleaned" before passing it down to the query.
In case there's no match, it'll fail, as expected.

# Testing

1. Open the app
2. Copy any existing order id, such as `0xc31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05`
3. Make any char uppercase
4. Paste it into the search bar and search

- [ ] The order should load

5. On the order details page URL, make any char uppercase:
screenshot_2021-03-23_13-47-09
6. Hit enter

- [ ] The same order should load

### CODE REVIEW

**Comment by biocom** [comment]
No CI link?

**Comment by anxolin** [comment]
> No CI link?

Im re-running the CI, the link was not published...

**Comment by anxolin** [comment]
@biocom link is back

I think it might be because there's no PR yet when the last commit is pushed

1. push commit "my last commit"
2. Github Actions do its magic. When it tries to decide where to push the build, it checks if there's an associated PR, if there is not, it doesn't do the PRaul thing
3. Later we create the PR, but the build was already done

the above is my theory, we can see how to improve it. @biocom if we find this, we can hit the button to build again and see if that solves the issue

File: src/hooks/useOperatorOrder.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ async function _getOrder(
   networkIdSearchListRemaining: Network[] = NETWORK_ID_SEARCH_LIST,
 ): Promise<GetOrderResult> {
   // Get order
-  const order = await getOrder({ networkId, orderId })
+  const order = await getOrder({ networkId, orderId: orderId.toLowerCase() })
```
Comment (anxolin) [inline src/hooks/useOperatorOrder.ts:33]: why not doing this in the impl? This way we dont need to be making the fix in every use of the API or hook

image

**Review by anxolin — COMMENTED** [review]
Works great!
just a suggestion on where to do the fix

**Comment by biocom** [comment]
Nice @alfetopito and very important to have!

Bonus for fool proof resilience:
- `"0XC31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05"` -> not found (trim pre- and appended " and ' characters) in case someone copies it from somewhere. Could be trimmed already on pasting I suppose, like we trim the spaces on input.
 - Pasting a `nbsp` (empty space) before, after or in between results in an error => https://pr323--gpui.review.gnosisdev.com/orders/%200XC31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05/ (adds the `%20`) - Again we could trim these characters from the URL address bar input (the regular <Input> already filters this out I believe).
 
 Btw unfortunately this doesn't work either :trollface: :
 - https://pr323--gpui.review.gnosisdev.com/orders/🚀🚀🚀🚀🚀🚀🚀🚀🚀0XC31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05🚀🚀🚀🚀🚀🚀🚀🚀🚀/

File: src/hooks/useOperatorOrder.ts (hunk 1 above)
Comment (alfetopito) [reply src/hooks/useOperatorOrder.ts:33]: I wanted to keep the API "pure". Who knows, maybe we do need a case sensitive search :shrug: 

But no strong reason for that. Will update.

**Comment by alfetopito** [comment]
> Nice @alfetopito and very important to have!
> 
> Bonus for fool proof resilience:
> 
>     * `"0XC31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05"` -> not found (trim pre- and appended " and ' characters) in case someone copies it from somewhere. Could be trimmed already on pasting I suppose, like we trim the spaces on input.

Makes sense, will add this

> 
>     * Pasting a `nbsp` (empty space) before, after or in between results in an error => https://pr323--gpui.review.gnosisdev.com/orders/%200XC31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05/ (adds the `%20`) - Again we could trim these characters from the URL address bar input (the regular  already filters this out I believe).

Not sure about this one...
Maybe if instead we do a regex match on the format `0x\d{num of chars}` and extract it.
What to do when it doesn't match? Redirect the bad id to fail? Disable the search button?

> 
> 
> Btw unfortunately this doesn't work either :trollface: :
> 
>     * [https://pr323--gpui.review.gnosisdev.com/orders/rocketrocketrocketrocketrocketrocketrocketrocketrocket0XC31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05rocketrocketrocketrocketrocketrocketrocketrocketrocket/](https://pr323--gpui.review.gnosisdev.com/orders/%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%800XC31de83790b0a0cff23bda533ab488fda0029fb7cafffe6d0b0a7d06bf957f0b9367280befb2464064d4db7ffa6440ede651df48604beb05%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80/)

Oh c'mon! If you do that, you are asking to not have your order found. I refuse! =P

File: src/hooks/useOperatorOrder.ts (hunk 1 above)
Comment (alfetopito) [reply src/hooks/useOperatorOrder.ts:33]: Considering the cases Michel added below, I think we might want to do this somewhere else.
While only lowercase should be fine in the API, the extra cleaning/regex matching don't belong there.

I'm thinking about adding it as a hook encapsulating `useParams`, and updating the url after cleaning the id

**Comment by biocom** [comment]
> Not sure about this one...
> Maybe if instead we do a regex match on the format `0x\d{num of chars}` and extract it.
> What to do when it doesn't match? Redirect the bad id to fail? Disable the search button?

Probably too much work by then...especially given the regex matching might have some unintended side effects in some scenarios? Like your approach though.

> Oh c'mon! If you do that, you are asking to not have your order found. I refuse! =P

:trollface: :trollface: WE HAZZ EMOOOOJI's :trollface:  :trollface:

File: src/hooks/useOperatorOrder.ts (hunk 1 above)
Comment (alfetopito) [reply src/hooks/useOperatorOrder.ts]: Done in a hook now

**Comment by alfetopito** [comment]
> > Not sure about this one...
> > Maybe if instead we do a regex match on the format `0x\d{num of chars}` and extract it.
> > What to do when it doesn't match? Redirect the bad id to fail? Disable the search button?
> 
> Probably too much work by then...especially given the regex matching might have some unintended side effects in some scenarios? Like your approach though.
> 
> > Oh c'mon! If you do that, you are asking to not have your order found. I refuse! =P
> 
> :trollface: :trollface: WE HAZZ EMOOOOJI's :trollface: :trollface:

Try again ;)

**Comment by anxolin** [comment]
@MareenG I guess you closed the PR thinking that it was the issue. If you want you can close the issue, and approve this PR.

image

**Review by MareenG — APPROVED** [review]

File: src/hooks/useOrderId.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+  // Ignores case
+  const regexMatch = orderId.match(/(0x[0-9a-f]{112})/i)
+
+  // Get extracted order id from the match, if any
+  const sanitizedOrderId = (regexMatch && regexMatch[0]?.toLowerCase()) || orderId.toLowerCase()
+
+  // If there's an orderId in the url AND it's not yet nice, update the URL
+  if (regexMatch && sanitizedOrderId !== orderId) {
+    // TODO: is there a better way to do this?
+    const newPath = url.replace(orderId, sanitizedOrderId)
```
Comment (anxolin) [inline src/hooks/useOrderId.ts:24]: Im sure there is, you already decided for a parameter name `orderId`, so it would be to update the params by the parameter name. Not sure exactly how is done, but worse case you can get all the params, and merge the 2 objects.

**Review by biocom — APPROVED** [review]

File: src/hooks/useOrderId.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+ * Sanitizes it and updates the URL, if any
+ *
+ * @returns Sanitized order id
+ */
+export function useOrderId(): string {
+  const { orderId } = useParams<{ orderId: string }>()
+  const { url } = useRouteMatch()
+  const history = useHistory()
+
+  // Allows any kind of crap in the orderId, as long as there is a valid and continuous order id in it
```
[the remark this answers is not in the document]
Comment (alfetopito) [reply src/hooks/useOrderId.ts:14]: Do we have mature filter turned on for code comments?

File: src/hooks/useOrderId.ts (hunk 2 above)
Comment (alfetopito) [reply src/hooks/useOrderId.ts:24]: The other option I tried was to replace the path, which is `:orderId`
But that mean that if we ever change the route, we'll have to update it here too.
This hacky way works regardless of the path, replacing the old value with the new one.

File: src/hooks/useOrderId.ts [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+  // Ignores case
+  const regexMatch = orderId.match(/(0x[0-9a-f]{112})/i)
```
[the remark this answers is not in the document]
Comment (alfetopito) [reply src/hooks/useOrderId.ts:16]: We'll have to update this when we get around to short ids, but that'll depend on the backend supporting it.
Anyway, I'll update the regex as suggested making the `0x` optional

File: src/hooks/useOrderId.ts [hunk 5]
```diff
@@ -0,0 +1,29 @@
+import { useHistory, useParams, useRouteMatch } from 'react-router'
+
+/**
+ * Fetches order id from url parameters
+ * Sanitizes it and updates the URL, if any
+ *
+ * @returns Sanitized order id
+ */
+export function useOrderId(): string {
```
[the remark this answers is not in the document]
Comment (alfetopito) [reply src/hooks/useOrderId.ts:9]: https://github.com/gnosis/gp-ui/pull/327
