### PR TITLE
251/update contract address

### LINKED ISSUE #251: Contract address is wrong
The Contract address in the Explorer still points to GPv1

We should make it point to GPv2, but also, we should probably add the allowance manager too

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #251

Updating explorer contract address

Added both Settlement and Allowance manage addresses to footer
@biocom please review placement/wording

## Mobile
screenshot_2021-03-05_13-24-31
## Condensed
screenshot_2021-03-05_13-24-22
## Fully expanded
screenshot_2021-03-05_13-24-12

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Great PR! 
@biocom, could you make a suggestion, on how to show it nicer? Could be as a PR starting from this branch, or wireframe, whatever is easier. 

I feel is a bit verbose this proposal. Anyways, approving, cause it works great and I like the refactor.

File: src/api/deposit/batchExchangeAddresses.ts [hunk 1]
```diff
@@ -1,15 +1,11 @@
...
-  const networkInfo = networks['BatchExchange'][networkId]
-  return networkInfo ? networkInfo.address : ''
-}
+import { getGpV1ContractAddress } from 'utils/contract'
 
 const addressesByNetwork = {
-  [Network.Rinkeby]: _getAddress(Network.Rinkeby),
-  [Network.Mainnet]: _getAddress(Network.Mainnet),
-  [Network.xDAI]: _getAddress(Network.xDAI),
+  [Network.Rinkeby]: getGpV1ContractAddress(Network.Rinkeby) as string,
```
Comment (W3stside) [inline src/api/deposit/batchExchangeAddresses.ts:6]: why is the `as` required? can you copy the return value of the previous function?

File: src/components/layout/GenericLayout/Footer/index.tsx [hunk 2]
```diff
@@ -97,21 +105,32 @@ export interface FooterType {
...
-      {contractAddress && networkId ? (
-        <VerifiedButton
-          type="contract"
-          identifier={contractAddress}
-          networkId={networkId}
-          label={verifiedText ? verifiedText : 'View contract'}
-        />
-      ) : null}
+      <ContractsWrapper>
+        {settlementContractAddress ? (
```
Comment (W3stside) [inline src/components/layout/GenericLayout/Footer/index.tsx:117]: can just be `settlementContractAddress && <Component />`

same for below

File: src/components/layout/GenericLayout/Footer/index.tsx [hunk 3]
```diff
@@ -97,21 +105,32 @@ export interface FooterType {
...
+            networkId={networkId}
+            label={'View settlement contract'}
+          />
+        ) : null}
+        {allowanceManagerContractAddress ? (
+          <VerifiedButton
+            type="contract"
+            identifier={allowanceManagerContractAddress}
+            networkId={networkId}
+            label={'View allowance manager contract'}
```
Comment (W3stside) [inline src/components/layout/GenericLayout/Footer/index.tsx:130]: don't need `{` when using `string` props (unless template stings)

File: src/utils/contract.ts [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+  [networkId: string]: { address: string }
+}
+
+type OptionalNetwork = Network | undefined
+
+export function getContractAddressFromNetworkInfo(
+  network: OptionalNetwork,
+  networkInfo: ContractNetworkInfo,
+): string | null {
+  if (!network) {
```
Comment (W3stside) [inline src/utils/contract.ts:16]:
```suggestion
  if (!network || !networkInfo[network]?.address) {
```

File: src/utils/contract.ts [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+    return null
+  }
+  return networkInfo[network]?.address || null
```
Comment (W3stside) [inline src/utils/contract.ts:19]:
```suggestion
  return networkInfo[network]?.address
```

**Review by W3stside — APPROVED** [review]

File: src/api/deposit/batchExchangeAddresses.ts (hunk 1 above)
Comment (alfetopito) [reply src/api/deposit/batchExchangeAddresses.ts:6]: That's because it returns `null` and the original function returns only `string`.
Did not want to change for legacy reasons (update gp-v1 code).

What I can do is to - instead of casting to string - return an empty string: `getGpV1ContractAddress(Network.Rinkeby) || ''`

Will update in another PR

Comment (alfetopito) [reply src/api/deposit/batchExchangeAddresses.ts:6]: https://github.com/gnosis/gp-ui/pull/279

**Comment by MareenG** [comment]
Are the mock ups a hard criteria?
The condensed form in the web browser looks like the mobile version.

**Comment by anxolin** [comment]
> Are the mock ups a hard criteria?
> The condensed form in the web browser looks like the mobile version.

I didn't get the question, sorry

**Comment by MareenG** [comment]
Sorry, what I meant is if it has to look like the mock up listed above. 
When I condense my browser I get this layout:
Bildschirmfoto 2021-03-18 um 08 58 42

and not this one:

Bildschirmfoto 2021-03-18 um 08 58 46

**Comment by biocom** [comment]
@MareenG The former (condensed layout) is for mobile and intended to be rendered like that (if that answers your question).

My only observation is the viewport on table size resolutions. For that I would suggest to use the mobile version of the footer.

**Comment by MareenG** [comment]
Yes, thank you
